{
 "title": "Energy System Simulation (EOS)",
 "tags": [
  "energy",
  "simulation",
  "eos"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Overall Energy Costs (€)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"energy_simulation\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"energy_costs\")\n  |> filter(fn: (r) => r.simulation == \"today-energy-simulation\")\n  |> filter(fn: (r) => r._field == \"grid_net_eur\")\n  |> cumulativeSum()\n  |> yield(name: \"net\")"
    }
   ]
  },
  {
   "title": "Import (Eur)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"energy_simulation\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"energy_costs\")\n  |> filter(fn: (r) => r.simulation == \"today-energy-simulation\")\n  |> filter(fn: (r) => r._field == \"grid_import_eur\")\n  |> cumulativeSum()\n  |> yield(name: \"import\")"
    }
   ]
  },
  {
   "title": "Export (€)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 9, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"energy_simulation\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"energy_costs\")\n  |> filter(fn: (r) => r.simulation == \"today-energy-simulation\")\n  |> filter(fn: (r) => r._field == \"grid_export_eur\")\n  |> cumulativeSum()\n  |> yield(name: \"export\")"
    }
   ]
  },
  {
   "title": "Grid Transfer",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "query": "from(bucket: \"energy_simulation\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"energy_flow\")\n  |> filter(fn: (r) => r.simulation == \"today-energy-simulation\")\n  |> filter(fn: (r) => r._field == \"imported_kwh\" or r._field == \"exported_kwh\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Energy Flow",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "query": "from(bucket: \"energy_simulation\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"energy_flow\")\n  |> filter(fn: (r) => r.simulation == \"today-energy-simulation\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Energy Price (/kWh)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "targets": [
    {
     "query": "from(bucket: \"energy_simulation\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"forecast_price\")\n    |> filter(fn: (r) => r._field == \"import_price_eur\" or r._field == \"export_price_eur\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Battery Storage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "query": "from(bucket: \"energy_simulation\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"battery_storage\")\n  |> filter(fn: (r) => r.simulation == \"today-energy-simulation\")\n  |> filter(fn: (r) => r.type == \"BATTERY\")\n  |> filter(fn: (r) => r._field == \"stored_energy_kwh\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> keep(columns: [\"_time\", \"_value\", \"device\"])\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Accu %",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "query": "from(bucket: \"energy_simulation\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"battery_storage\")\n  |> filter(fn: (r) => r.simulation == \"today-energy-simulation\")\n  |> filter(fn: (r) => r.type == \"ELECTRIC_CAR\")\n  |> filter(fn: (r) => r._field == \"storage_percentage\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> keep(columns: [\"_time\", \"_value\", \"device\"])\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Energy Costs (EUR)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "targets": [
    {
     "query": "from(bucket: \"energy_simulation\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"energy_costs\")\n  |> filter(fn: (r) => r.simulation == \"today-energy-simulation\")\n  |> filter(fn: (r) => r._field == \"grid_import_eur\" or r._field == \"grid_export_eur\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  }
 ]
}