name: Create PR to main from dependabot-integration

on:
  push:
    branches: [ dependabot-integration ]
  workflow_dispatch:

jobs:
  create-pr-to-main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout dependabot-integration
        uses: actions/checkout@v4
        with:
          ref: dependabot-integration
          fetch-depth: 0

      - name: Check if main branch exists and get diff
        id: check_diff
        run: |
          git fetch origin main:main || echo "main branch not found"
          
          # Check if there are differences between dependabot-integration and main
          if git diff --quiet main..dependabot-integration; then
            echo "No differences found between branches"
            echo "has_changes=false" >> $GITHUB_OUTPUT
          else
            echo "Changes found between branches"
            echo "has_changes=true" >> $GITHUB_OUTPUT
            
            # Get commit messages for PR description
            COMMITS=$(git log main..dependabot-integration --oneline --no-merges)
            echo "commits<<EOF" >> $GITHUB_OUTPUT
            echo "$COMMITS" >> $GITHUB_OUTPUT
            echo "EOF" >> $GITHUB_OUTPUT
          fi

      - name: Create Pull Request to main
        if: steps.check_diff.outputs.has_changes == 'true'
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          base: main
          head: dependabot-integration
          title: "Sync dependency updates from dependabot-integration to main"
          body: |
            ## Dependency Updates Sync
            
            This PR syncs the latest dependency updates from `dependabot-integration` branch to `main`.
            
            ### Changes included:
            ```
            ${{ steps.check_diff.outputs.commits }}
            ```
            
            ### Review Guidelines:
            - ✅ All tests should pass
            - ✅ Review any breaking changes in dependencies
            - ✅ Check for security updates
            
            Auto-generated by GitHub Actions.
          labels: |
            dependencies
            auto-sync
          reviewers: |
            tbergmann
